services:
# アプリ用のDockerに入る時の名前
  review-php-apache:
    build:
      context: ./php-apache
      dockerfile: Dockerfile
    ports:
      # - [ 1 ]:[ 2 ]
      - 8888:80
    volumes:
      - type: bind
        # source: [ 3 ]
        source: "./php-apache/000-default.conf"
        target: "/etc/apache2/sites-enabled/000-default.conf"
      - type: bind
        source: "./php-apache/app"
        # target: [ 4 ]
        target: "/var/www/docker_review"
    depends_on:
      - review-mysql
  # DBのDockerに入る時の名前
  review-mysql:
    # image: [ 5 ]
    image: mysql:8
    platform: linux/x86_64
    environment:
      - MYSQL_ROOT_PASSWORD=e2QNqCUd
      - MYSQL_DATABASE=docker_review

